Improved how EBS dev is identified. Add loop to check instance connectivity. Removed empty variables so nounset and errexit can be used, resolves #1

diff --git a/cellrangerAWS b/cellrangerAWS
--- a/cellrangerAWS
+++ b/cellrangerAWS
@@ -1,15 +1,18 @@
 #! /bin/bash
 
-set -x -o pipefail
+set -x -o nounset -o pipefail -o errexit
 
 
 
 # Inputs
+INPUT="none"
+OUTPUT="none"
+KEY="none"
 PROJECT="cellranger"
 EC2_TYPE="t2.2xlarge"
 AMI="ami-0b223f110bbbd4a9e"
-VOLUME_SIZE=300
 CREATE_VOL=true
+VOLUME_SIZE=50
 ZONE="us-west-2a"
 SECURITY_GROUP="sg-00cf9318d9719735d"
 SUBNET="subnet-083a3a855e543ee1c"
@@ -26,13 +29,13 @@ $0 [OPTIONS]
 
 OPTIONS
 -h, display this message
--i, input directory containing fastq files and config.yaml or ID for snapshot containing data
--o, output directory
+-i, path to input directory containing fastq files and config.yaml or ID for snapshot containing data
+-o, path to output directory
 -p, project name
 -k, path to AWS private key
--t, EC2 instance type (default is $EC2_TYPE)
--s, size of EBS volume (default is $VOLUME_SIZE GB)
--a, ID for machine image configured to run cellranger (default is $AMI)
+-t, EC2 instance type (default is "$EC2_TYPE")
+-s, size of EBS volume in GB, by default this is set based on the size of the fastqs present in the input directory
+-a, ID for machine image configured to run cellranger (default is "$AMI")
 
     """
 }
@@ -43,7 +46,7 @@ OPTIONS
 while getopts ":hi:o:p:k:t:s:a:" args
 do
     case "$args" in
-        h)
+        help)
             usage
             exit 0
             ;;
@@ -86,7 +89,7 @@ do
     esac
 done
 
-if [[ -z "$INPUT" || -z "$OUTPUT" || -z "$KEY" ]]
+if [[ "$INPUT" == "none" || "$OUTPUT" == "none" || "$KEY" == "none" ]]
 then
     echo -e "\nERROR: arguments are required for -i, -o, and -k"
 
@@ -96,28 +99,24 @@ fi
 
 
 
-# Check instance/volume state
-check_state() {
+# Check instance/volume status
+check_status() {
     local input_fun=$1
+    local id=$2
 
     for i in $(seq 1 60)
     do
-        state=$("$input_fun")
-
-        if [[ ! -z "$state" ]]
+        if "$input_fun" "$id" | grep --quiet "$id"
         then
-            break
-        fi
-
-	if [[ i == 60 ]]
-        then
-            echo -e "\nERROR: could not find $input_fun\n"
-
-            exit 1
+            return 0
         fi
 
         sleep 5
     done
+
+    echo -e "\nERROR: timed out waiting for $input_fun\n"
+
+    exit 1
 }
 
 
@@ -127,7 +126,6 @@ check_state() {
 # this create new VPC, security group, subnet, and internet gateway. Activate
 # public IP for subnet, activate public DNS for VPC, attach VPC to internet
 # gateway, modify route table for VPC.
-
 launch_ec2() {
     local ami="$1"
     local ec2_type="$2"
@@ -135,6 +133,7 @@ launch_ec2() {
     local security_group="$4"
     local subnet="$5"
     local key_name=$(basename -s .pem "$KEY")
+
 
     # Launch EC2 instance
     local ec2=$(
@@ -152,12 +151,11 @@ launch_ec2() {
 
     running_ec2() {
         aws ec2 describe-instances \
-            --instance-id "$ec2" \
-            --filters Name=instance-state-name,Values=running \
-            | grep -o "$ec2"
+            --instance-id "$1" \
+            --filters Name=instance-state-name,Values=running
     }
 
-    check_state running_ec2
+    check_status running_ec2 "$ec2"
 
 
     # Return ID for launched EC2 instance
@@ -166,10 +164,75 @@ launch_ec2() {
 
 
 
+# Retrieve public DNS for EC2 instance and check connectivity
+get_dns() {
+    local ec2="$1"
+
+    # Retrieve public IP to check connectivity
+    local ip=$(
+        aws ec2 describe-instances \
+            --instance-id "$ec2" \
+            | grep -E "PublicIpAddress" \
+            | grep -E -o "[0-9\.]+"
+    )
+
+    for i in $(seq 1 20)
+    do
+        # Ping IP
+        local packet_loss=$(
+            ping -c 10 "$ip" \
+                | grep -E -o "[0-9]+% packet loss" \
+                | grep -E -o "[0-9]+"
+        )
+
+        # Return public DNS for ssh
+        if [[ "$packet_loss" < 100 ]]
+        then
+            local dns=$(
+                aws ec2 describe-instances \
+                    --instance-id "$ec2" \
+                    | grep -E -o "ec2\-[[:alnum:]\.\-]+compute.amazonaws.com" \
+                    | head -n 1
+            )
+
+            echo "$USER@$dns"
+
+            return 0
+        fi
+    done
+
+    # If unable to ping IP, terminate instance
+    aws ec2 terminate-instances \
+        --instance-ids "$ec2"
+
+    echo "ERROR: unable to connect, terminating EC2 instance"
+
+    exit 1
+}
+
+
+    
+# Create and attach EBS volume to hold fastqs
 create_ebs() {
-    local ec2=$1
-    local volume_size=$2
-    local zone=$3
+    local input=$1
+    local ec2=$2
+    local vol_size=$3
+    local zone=$4
+    local ssh=$5
+
+
+    # Get list of attached devices, need this to identify newly attached device
+    old_devs=$(
+        ssh -o "StrictHostKeyChecking no" -i "$KEY" "$ssh" \
+            sudo fdisk -l \
+                | grep -E -o "/dev/[[:alnum:]]+" \
+                2>&1
+    )
+
+    old_devs=$(
+        echo $old_devs \
+            | sed 's/ /|/g'
+    )
 
 
     # Create EBS volume
@@ -177,7 +240,7 @@ create_ebs() {
     then
         local vol=$(
             aws ec2 create-volume \
-                --size "$volume_size" \
+                --size "$vol_size" \
                 --availability-zone "$zone" \
                 | grep -E -o "vol\-[[:alnum:]]+"
         )
@@ -193,12 +256,11 @@ create_ebs() {
 
     available_vol() {
         aws ec2 describe-volumes \
-            --volume-ids "$vol" \
-            --filters Name=status,Values=available \
-            | grep -o "$vol"
+            --volume-ids "$1" \
+            --filters Name=status,Values=available
     }
 
-    check_state available_vol
+    check_status available_vol "$vol"
 
 
     # Attach EBS volume
@@ -210,47 +272,37 @@ create_ebs() {
 
     attached_vol() {
         aws ec2 describe-volumes \
-            --volume-ids "$vol" \
-            --filters Name=attachment.status,Values=attached \
-            | grep -o "$vol"
+            --volume-ids "$1" \
+            --filters Name=attachment.status,Values=attached
     }
 
-    check_state attached_vol
+    check_status attached_vol "$vol"
 
     sleep 60
 
 
-    # Return ID for attached EBS volume
-    echo "$vol"
-}
-
-
-
-transfer_data() {
-    local input="$1"
-    local vol="$2"
-    local volume_size="$3"
-    local ssh="$4"
-    local snap_name="$5"
-
-
-    # Retrieve device path for EBS volume
-    dev_path=$(
-        ssh -o "StrictHostKeyChecking no" -i "$KEY" "$ssh" \
+    # Identify device path for EBS volume
+    new_devs=$(
+        ssh -i "$KEY" "$ssh" \
             sudo fdisk -l \
-                | grep -E -o "^Disk .+$volume_size GiB" \
+                | grep -E "^Disk .+$vol_size GiB" \
                 | grep -E -o "/dev/[[:alnum:]]+" \
                 2>&1
+    )
+    
+    dev_path=$(
+        echo "$new_devs" \
+            | grep -E -v "$old_devs"
     )
 
 
     # Format new EBS volume
     if [[ "$CREATE_VOL" == true ]]
     then
-        ssh -o "StrictHostKeyChecking no" -i "$KEY" "$ssh" bash <<EOF
-            sudo parted "$dev_path" mklabel gpt
-	    sudo parted -a opt "$dev_path" mkpart primary ext4 0% 100%
-	    sudo mkfs.ext4 -F "$dev_path"
+        ssh -i "$KEY" "$ssh" bash <<EOF
+            sudo parted "$dev_path" mklabel gpt > /dev/null
+	    sudo parted -a opt "$dev_path" mkpart primary ext4 0% 100% > /dev/null
+	    sudo mkfs.ext4 -F "$dev_path" > /dev/null
 EOF
 
     fi
@@ -261,10 +313,24 @@ EOF
         sudo mkdir -p /mnt/EBS
         sudo mount "$dev_path" /mnt/EBS
         sudo mkdir -p /mnt/EBS/DATA
-        sudo chmod -R 777 /mnt
+        sudo chmod -R 777 /mnt/EBS
 EOF
 
-    local snap_id="$input"
+
+    # Return ID for attached EBS volume
+    echo "$vol"
+}
+
+
+
+# Transfer data to mounted EBS volume
+transfer_data() {
+    local input="$1"
+    local vol="$2"
+    local ssh="$3"
+    local snap_name="$4"
+    local snap="$input"
+
 
     if [[ "$CREATE_VOL" == true ]]
     then
@@ -276,7 +342,7 @@ EOF
                 --description "$snap_name" \
                 --volume-id "$vol" \
 	        | grep -E -o "snap\-[[:alnum:]]+"
-    	    )
+    	)
     fi
 
 
@@ -286,32 +352,32 @@ EOF
 
 
 
+# Terminate EC2 instance, create snapshot to save data, delete EBS volume
 terminate_ec2() {
     local ec2="$1"
     local vol="$2"
     local snap="$3"
 
+
     # Terminate EC2 instance
     completed_snap() {
         aws ec2 describe-snapshots \
-            --snapshot-ids "$snap" \
-            --filters Name=status,Values=completed \
-            | grep -E -o "$snap"
+            --snapshot-ids "$1" \
+            --filters Name=status,Values=completed
     }
 
-    check_state completed_snap
+    check_status completed_snap "$snap"
 
     aws ec2 terminate-instances \
         --instance-ids "$ec2"
 
     terminated_ec2() {
         aws ec2 describe-instances \
-            --instance-id "$ec2" \
-            --filters Name=instance-state-name,Values=terminated \
-            | grep -o "$ec2"
+            --instance-id "$1" \
+            --filters Name=instance-state-name,Values=terminated
     }
 
-    check_state terminated_ec2
+    check_status terminated_ec2 "$ec2"
 
 
     # Delete EBS volume
@@ -330,10 +396,27 @@ $0 -i $snap -o $OUTPUT -k $KEY
 
 
 
+# Main function
 main() {
-
+   
     # Set project name
-    project_name="$PROJECT"_$(date +%Y%m%d-%H:%M:%S)
+    project_name="$PROJECT"_$(date +%Y%m%d-%H%M%S)
+
+
+    # Set EBS volume size
+    data_size=$(
+        du -shc -BG "$INPUT" \
+            | grep "total" \
+            | grep -E -o "[0-9]+"
+    )
+
+    volume_size=$(expr "$data_size" \* 2)
+
+    if [[ "$VOLUME_SIZE" > "$volume_size" ]]
+    then
+        volume_size="$VOLUME_SIZE"
+    fi
+
 
     # Launch EC2 instance
     ec2_id=$(
@@ -345,47 +428,39 @@ main() {
             "$SUBNET"
     )
 
+
+    # Retrieve public DNS for ssh and check connectivity
+    # Public DNS is not listed in run-instances output
+    ec2_ssh=$(get_dns "$ec2_id")
+
+
     # Create EBS volume
     vol_id=$(
         create_ebs \
+            "$INPUT" \
             "$ec2_id" \
-            "$VOLUME_SIZE" \
-            "$ZONE"
+            "$volume_size" \
+            "$ZONE" \
+	    "$ec2_ssh"
     )
 
-    # Retrieve public DNS for ssh
-    # Public DNS is not listed in run-instances output
-    pub_dns=$(
-        aws ec2 describe-instances \
-            --instance-id "$ec2_id" \
-            | grep -E -o "ec2\-[[:alnum:]\.\-]+compute.amazonaws.com" \
-            | head -n 1
-    )
 
-    ec2_ssh="$USER@$pub_dns"
-
-    # Mount EBS volume
+    # Transfer data to EBS volume
     snap_id=$(
         transfer_data \
             "$INPUT" \
             "$vol_id" \
-            "$VOLUME_SIZE" \
             "$ec2_ssh" \
 	    "$project_name"
     )
 
 
-
-    # Run cellranger
+    # Run cellranger and transfer results
     ssh -i "$KEY" "$ec2_ssh" \
-        bash /home/"$USER"/PIPELINE/snakecharmer.sh
+        bash "/home/$USER/PIPELINE/snakecharmer.sh"
 
-    scp -r -i "$KEY" "$ec2_ssh":/home/"$USER"/PIPELINE/RESULTS/logs "$OUTPUT"
-    #scp -r -i "$KEY" "$ec2_ssh":/home/"$USER"/PIPELINE/RESULTS/* "$OUTPUT"     # NEED TO CHANGE THIS!!!!!
-
-    # REMOVE AFTER TESTING!!!!
-    #exit 0
-
+    rsync -r -e "ssh -i $KEY" --exclude possorted_genome_bam.bam* \
+        "$ec2_ssh:/mnt/EBS/RESULTS/"* "$OUTPUT"
 
 
     # Terminate EC2 instance
